import React from 'react';
import { TrendingUp, TrendingDown } from 'lucide-react';
import { Skeleton } from './atoms';

// Header stats strip shared across the whole Social section. The parent
// SocialLayout fetches the data once on mount and feeds it down.
export default function StatsStrip({ data }) {
    const cards = [
        { key: 'activeCampaigns',   label: 'Active campaigns',                value: data?.activeCampaigns,    delta: data?.deltas?.activeCampaigns },
        { key: 'pendingVariants',   label: 'Variants awaiting review',        value: data?.pendingVariants,    delta: data?.deltas?.pendingVariants },
        { key: 'scheduledThisWeek', label: 'Posts scheduled this week',       value: data?.scheduledThisWeek,  delta: data?.deltas?.scheduledThisWeek },
        { key: 'leadsThisWeek',     label: 'Leads generated by ads this week',value: data?.leadsThisWeek,      delta: data?.deltas?.leadsThisWeek },
    ];

    if (data === null || data === undefined) {
        return (
            <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
                {cards.map((c) => (
                    <div key={c.key} className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5 space-y-3">
                        <Skeleton className="h-3 w-32" />
                        <Skeleton className="h-9 w-20" />
                        <Skeleton className="h-3 w-16" />
                    </div>
                ))}
            </div>
        );
    }

    return (
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
            {cards.map((c) => <StatCard key={c.key} {...c} />)}
        </div>
    );
}

function StatCard({ label, value, delta }) {
    const hasDelta = typeof delta === 'number';
    const up = hasDelta && delta >= 0;
    return (
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5">
            <p className="text-[10px] font-bold uppercase tracking-[0.22em] text-gray-600">{label}</p>
            <p className="text-3xl font-bold text-gray-900 tracking-tight mt-2 tabular-nums">{value?.toLocaleString?.() ?? '—'}</p>
            {hasDelta && (
                <p className={`mt-2 inline-flex items-center gap-1 text-[11px] font-bold tabular-nums ${up ? 'text-emerald-700' : 'text-rose-700'}`}>
                    {up ? <TrendingUp size={12} /> : <TrendingDown size={12} />}
                    {up ? '+' : ''}{delta} vs last week
                </p>
            )}
        </div>
    );
}
